version: '3.8'

services:
  interview-helper:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - ENABLE_REQUEST_LOGGING=true
      - BACKUP_INTERVAL_HOURS=24
      - DATA_RETENTION_DAYS=365
      - SUPPORT_QUEUE_FILE=/app/data/support-queue.json
    volumes:
      - interview_data:/app/data
      - interview_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - interview-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - interview-helper
    networks:
      - interview-network
    restart: unless-stopped

  # Monitoring and logging (optional)
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 2 * * *  # Daily at 2 AM
    restart: unless-stopped

volumes:
  interview_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  interview_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

networks:
  interview-network:
    driver: bridge